export const SUPPORTED_PATTERNS = [
  'hammer',
  'inverted-hammer',
  'bullish-engulfing',
  'bearish-engulfing',
  'morning-star',
  'evening-star',
  'doji',
  'dragonfly-doji',
  'gravestone-doji',
  'spinning-top',
  'marubozu',
  'hanging-man',
  'shooting-star',
  'three-white-soldiers',
  'three-black-crows',
  'piercing-line',
  'dark-cloud-cover',
  'tweezer-top',
  'tweezer-bottom',
  'harami',
] as const;

export type SupportedPattern = (typeof SUPPORTED_PATTERNS)[number];

export const PATTERN_LABELS: Record<SupportedPattern, string> = {
  hammer: 'Hammer',
  'inverted-hammer': 'Inverted Hammer',
  'bullish-engulfing': 'Bullish Engulfing',
  'bearish-engulfing': 'Bearish Engulfing',
  'morning-star': 'Morning Star',
  'evening-star': 'Evening Star',
  doji: 'Doji',
  'dragonfly-doji': 'Dragonfly Doji',
  'gravestone-doji': 'Gravestone Doji',
  'spinning-top': 'Spinning Top',
  marubozu: 'Marubozu',
  'hanging-man': 'Hanging Man',
  'shooting-star': 'Shooting Star',
  'three-white-soldiers': 'Three White Soldiers',
  'three-black-crows': 'Three Black Crows',
  'piercing-line': 'Piercing Line',
  'dark-cloud-cover': 'Dark Cloud Cover',
  'tweezer-top': 'Tweezer Top',
  'tweezer-bottom': 'Tweezer Bottom',
  harami: 'Harami',
};
